# fly.toml app configuration file generated for casbytes on 2024-04-24T00:21:48+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'casbytes'
primary_region = 'lhr'

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source="data"
  destination="/data"

[experimental]
  auto_rollback = true
  enable_consul = true

[[services.tcp_checks]]
  grace_period = "6s"
  interval = "15s"
  restart_limit = 0
  timeout = "7s"

[[services.http_checks]]
  interval = 10000
  grace_period = "6s"
  method = "get"
  path = "/"
  protocol = "http"
  timeout = 2000
  tls_skip_verify = false
  [services.http_checks.headers]

[[services.http_checks]]
  interval = 10000
  grace_period = "6s"
  method = "get"
  path = "/healthcheck"
  protocol = "http"
  timeout = 2000
  tls_skip_verify = false
  [services.http_checks.headers]


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

