# fly.toml app configuration file generated for casbytes on 2024-04-24T00:21:48+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'casbytes'
primary_region = 'lhr'
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services.ports]]
  handlers = ["tls", "http"]
  port = 443

# [[services.ports]]
#   handlers = ["http"]
#   port = 80
#   force_https = true

[mounts]
  source="data"
  destination="/data"

[experimental]
  auto_rollback = true
  enable_consul = true

# [[services.tcp_checks]]
#   grace_period = "10s"
#   interval = "15s"
#   restart_limit = 6
#   timeout = "5s"

# [[services.http_checks]]
#   interval = 10000
#   grace_period = "5s"
#   method = "get"
#   path = "/"
#   protocol = "http"
#   timeout = 5000
#   tls_skip_verify = false

# [[services.http_checks]]
#   interval = 10000
#   grace_period = "5s"
#   method = "get"
#   path = "/healthcheck"
#   protocol = "http"
#   timeout = 5000
#   tls_skip_verify = false


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

